### ISSUE TITLE
As a parent, I can view all of my child’s school events in my preferred digital agenda(s)

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#18]
- [x] iCal export button
- [x] Design and explanation about iCal export
#17 is merged into this one

**Comment by brucevansteenwinkel** [comment]
<img width="296" alt="schermafbeelding 2015-07-14 om 16 44 21" src="https://cloud.githubusercontent.com/assets/4647210/8676070/8fa5b5a8-2a47-11e5-83ab-03ad992ed573.png">

Button is pretty big and bold because it's one of our main features

When clicked: (PDF is optional)
<img width="356" alt="schermafbeelding 2015-07-14 om 16 44 24" src="https://cloud.githubusercontent.com/assets/4647210/8676106/a65a1910-2a47-11e5-9085-6f6362002569.png">

<img width="772" alt="schermafbeelding 2015-07-14 om 16 45 25" src="https://cloud.githubusercontent.com/assets/4647210/8676119/b27231ec-2a47-11e5-80bf-6014e222e702.png">

This page is W.I.P, it's an idea that Bert had, instead of a blank download page we could make a page where people get a mini tutorial on how to import it into there agenda. This is optional

**Comment by xavez** [comment]
I like this :+1:  -> to be tested whether people actually find the “export” button.

**Comment by xavez** [comment]
@Bertware said in #17 Tested export function, working

**Comment by xavez** [comment]
TODO
- @brucevansteenwinkel bezorgt image met help content
- @thgh implementeer minimale versie in HTML met image + link / url

**Comment by thgh** [comment]
@Bertware routes implementeren

**Comment by xavez** [comment]
Excellent, this works. Has some issues as @brucevansteenwinkel mentioned, but those will be separate github issues.
